services:
  dare_study:
    container_name: dare_study
    image: carol02r/dare_study
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=4000